### ISSUE TITLE
Provide source for the demo

### ISSUE THREAD

**Issue by mgwalker** [bcbcarl/react-c3js#25]
Can you provide a repo that contains the source for the demo site?  "View source" isn't very useful for compiled React apps.  😄

**Comment by CASandmann** [comment]
You're right that it would be helpful to see more examples of this library in use rather than just having general documentation and end products for examples.

However, if you want to look at the components used on the page, you can download the React Developer Tools plugin [for Chrome](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) or [for Firefox](https://addons.mozilla.org/en-us/firefox/addon/react-devtools/).

**Comment by bcbcarl** [comment]
Here's the source for the demo site.
https://github.com/bcbcarl/react-c3js/tree/master/docs/src
